services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: .
    container_name: product_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env

volumes:
  pgvector_data: {}